### ISSUE TITLE
Slight update in header font needed.

### ISSUE THREAD

**Issue by jeremiahjordanisaacson** [NuevoFoundation/workshops#293]
Please update the fonts used for the header links to match the same font used on the homepage for Nuevo Foundation.

In review, it looks like it's just a slightly different version of Lato.

Current homepage
<img width="949" alt="image" src="https://user-images.githubusercontent.com/777517/173256372-f9e67db0-56b3-4465-bbc8-c5766d5d7613.png">

Recently changed workshops site font
<img width="956" alt="image" src="https://user-images.githubusercontent.com/777517/173256377-c96e55e8-d601-49ba-8dc4-bf565d5fb803.png">

**Comment by jruales** [comment]
@jeremiahjordanisaacson I'm seeing that the homepage (https://nuevofoundation.org/what-we-do) is actually not including the lato-semibold font correctly, so it's falling back to `sans-serif`. You can see this because if you intentionally use an incorrect font family instead of lato-semibold, the font remains the same.

There are two options:
* I change header buttons on the Workshops site to use the generic `sans-serif` font
* Whoever manages the main site updates it to properly include the Lato or lato-semibold font

Which one should we do?

**Comment by jeremiahjordanisaacson** [comment]
The goal is to have the Lato font used. If that font is loading for the workshops site, then it sounds like a problem with the NF website (main landing site). If that's the case, I'll have to resolve it and investigate as to why the Lato font isn't loading.
